import type { SymbolInfo } from "./symbols";

// A stable set of large, well-known constituents per SPDR sector ETF — not
// the official, exhaustive (and constantly reweighted) holdings list, which
// isn't available free. Enough names to meaningfully rank movers within a
// sector.
export const SECTOR_CONSTITUENTS: Record<string, SymbolInfo[]> = {
  XLK: [
    { symbol: "AAPL", name: "Apple" },
    { symbol: "MSFT", name: "Microsoft" },
    { symbol: "NVDA", name: "Nvidia" },
    { symbol: "AVGO", name: "Broadcom" },
    { symbol: "ORCL", name: "Oracle" },
    { symbol: "CRM", name: "Salesforce" },
    { symbol: "ADBE", name: "Adobe" },
    { symbol: "AMD", name: "AMD" },
  ],
  XLF: [
    { symbol: "JPM", name: "JPMorgan Chase" },
    { symbol: "BAC", name: "Bank of America" },
    { symbol: "WFC", name: "Wells Fargo" },
    { symbol: "GS", name: "Goldman Sachs" },
    { symbol: "MS", name: "Morgan Stanley" },
    { symbol: "SPGI", name: "S&P Global" },
    { symbol: "BLK", name: "BlackRock" },
    { symbol: "AXP", name: "American Express" },
  ],
  XLV: [
    { symbol: "LLY", name: "Eli Lilly" },
    { symbol: "UNH", name: "UnitedHealth" },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "ABBV", name: "AbbVie" },
    { symbol: "MRK", name: "Merck" },
    { symbol: "PFE", name: "Pfizer" },
    { symbol: "TMO", name: "Thermo Fisher" },
    { symbol: "ABT", name: "Abbott Labs" },
  ],
  XLY: [
    { symbol: "AMZN", name: "Amazon" },
    { symbol: "TSLA", name: "Tesla" },
    { symbol: "HD", name: "Home Depot" },
    { symbol: "MCD", name: "McDonald's" },
    { symbol: "NKE", name: "Nike" },
    { symbol: "LOW", name: "Lowe's" },
    { symbol: "SBUX", name: "Starbucks" },
    { symbol: "BKNG", name: "Booking Holdings" },
  ],
  XLP: [
    { symbol: "PG", name: "Procter & Gamble" },
    { symbol: "KO", name: "Coca-Cola" },
    { symbol: "PEP", name: "PepsiCo" },
    { symbol: "WMT", name: "Walmart" },
    { symbol: "COST", name: "Costco" },
    { symbol: "PM", name: "Philip Morris" },
    { symbol: "MDLZ", name: "Mondelez" },
    { symbol: "CL", name: "Colgate-Palmolive" },
  ],
  XLE: [
    { symbol: "XOM", name: "Exxon Mobil" },
    { symbol: "CVX", name: "Chevron" },
    { symbol: "COP", name: "ConocoPhillips" },
    { symbol: "SLB", name: "Schlumberger" },
    { symbol: "EOG", name: "EOG Resources" },
    { symbol: "MPC", name: "Marathon Petroleum" },
    { symbol: "PSX", name: "Phillips 66" },
    { symbol: "OXY", name: "Occidental Petroleum" },
  ],
  XLI: [
    { symbol: "GE", name: "GE Aerospace" },
    { symbol: "CAT", name: "Caterpillar" },
    { symbol: "RTX", name: "RTX Corp" },
    { symbol: "UNP", name: "Union Pacific" },
    { symbol: "HON", name: "Honeywell" },
    { symbol: "BA", name: "Boeing" },
    { symbol: "DE", name: "Deere & Co" },
    { symbol: "LMT", name: "Lockheed Martin" },
  ],
  XLB: [
    { symbol: "LIN", name: "Linde" },
    { symbol: "SHW", name: "Sherwin-Williams" },
    { symbol: "FCX", name: "Freeport-McMoRan" },
    { symbol: "ECL", name: "Ecolab" },
    { symbol: "APD", name: "Air Products" },
    { symbol: "NEM", name: "Newmont" },
    { symbol: "DD", name: "DuPont" },
    { symbol: "NUE", name: "Nucor" },
  ],
  XLU: [
    { symbol: "NEE", name: "NextEra Energy" },
    { symbol: "SO", name: "Southern Co" },
    { symbol: "DUK", name: "Duke Energy" },
    { symbol: "AEP", name: "American Electric Power" },
    { symbol: "SRE", name: "Sempra" },
    { symbol: "D", name: "Dominion Energy" },
    { symbol: "EXC", name: "Exelon" },
    { symbol: "XEL", name: "Xcel Energy" },
  ],
  XLRE: [
    { symbol: "PLD", name: "Prologis" },
    { symbol: "AMT", name: "American Tower" },
    { symbol: "EQIX", name: "Equinix" },
    { symbol: "WELL", name: "Welltower" },
    { symbol: "SPG", name: "Simon Property Group" },
    { symbol: "PSA", name: "Public Storage" },
    { symbol: "O", name: "Realty Income" },
    { symbol: "DLR", name: "Digital Realty" },
  ],
  XLC: [
    { symbol: "META", name: "Meta Platforms" },
    { symbol: "GOOGL", name: "Alphabet" },
    { symbol: "NFLX", name: "Netflix" },
    { symbol: "DIS", name: "Disney" },
    { symbol: "CMCSA", name: "Comcast" },
    { symbol: "TMUS", name: "T-Mobile US" },
    { symbol: "VZ", name: "Verizon" },
    { symbol: "T", name: "AT&T" },
  ],
};
